#This is docker-compose version for SWARM using OVERLAY network
# To run the services, use "docker stack deploy"

version: '3.3'
services:
    slave:
        image: "registry.nhan.com:5000/redis-sentinel:test"
        environment:
            MASTER_HOST: master
            MASTER_PORT: 6379
        ports:
            - "6380:6380"
        command:  "/tmp/redis-slave-init.sh redis-server /tmp/redis-slave.conf --protected-mode no --port 6380 --logfile /tmp/redis-6380.log --loglevel debug --appendonly yes"   
        deploy:
            replicas: 2
            resources:
                limits:
                    cpus: '0.1'
                    memory: 1G
                reservations:
                    cpus: '0.001'
                    memory: 500M 
            placement:
                constraints:
                  - node.hostname != centos2
        networks:
            - redis_network
networks:
    redis_network:
       external:
            name: redis_redis_network